/* Service worker: keeps the guide working offline. Generated by build_app.py. */
const CACHE = "npg-eaeba531cade";
const PHOTO_CACHE = "seed-photos-v1";
const ASSETS = [
  "./",
  "./index.html",
  "./manifest.webmanifest",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/maskable-512.png",
  "./icons/apple-touch-icon.png",
  "./icons/favicon-32.png",
  "./lib/leaflet.js",
  "./lib/leaflet.css",
  "./guides/Native_Plant_Cuttings_Guide_v1.6.pdf",
  "./guides/Native_Plant_Seed_Sowing_Guide_v1.6.pdf",
  "./guides/Native_Plant_Division_Guide_v1.2.pdf"
];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(ASSETS)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith("npg-") && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (req.mode === "navigate") {
    const isPage = url.pathname.endsWith("/") || url.pathname.endsWith("/index.html");
    if (!isPage) {
      // e.g. a PDF guide: serve the file itself, never the app page
      event.respondWith(caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req)));
      return;
    }
    event.respondWith(
      caches.match("./index.html").then((hit) => hit || fetch(req)).catch(() => caches.match("./index.html"))
    );
    return;
  }
  if (url.pathname.endsWith("/map-config.json")) {
    // map settings: always try the network first so a newly added key takes effect
    event.respondWith(fetch(req).then((res) => {
      if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); }
      return res;
    }).catch(() => caches.match(req, { ignoreSearch: true })));
    return;
  }
  if (url.pathname.includes("/seed-photos/")) {
    // team seed photos: show the saved copy straight away, refresh it from the network in the background
    event.respondWith(caches.open(PHOTO_CACHE).then((c) => c.match(req).then((hit) => {
      const net = fetch(req).then((res) => {
        if (res.ok) c.put(req, res.clone()); else if (res.status === 404) c.delete(req);
        return res;
      });
      if (hit) { net.catch(() => {}); return hit; }
      return net;
    })));
    return;
  }
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); }
      return res;
    }))
  );
});
